// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1707724424);
user_pref("app.update.lastUpdateTime.region-update-timer", 1707724424);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1707724424);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1707724454);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1707724424);
user_pref("browser.region.update.updated", 1707724401);
user_pref("browser.search.region", "IR");
user_pref("calendar.caldav.googleResync", 1707724397);
user_pref("calendar.list.sortOrder", "e7e8e370-4f03-488c-9dd7-2a496b88f79c");
user_pref("calendar.registry.e7e8e370-4f03-488c-9dd7-2a496b88f79c.calendar-main-default", true);
user_pref("calendar.registry.e7e8e370-4f03-488c-9dd7-2a496b88f79c.calendar-main-in-composite", true);
user_pref("calendar.registry.e7e8e370-4f03-488c-9dd7-2a496b88f79c.disabled", true);
user_pref("calendar.registry.e7e8e370-4f03-488c-9dd7-2a496b88f79c.name", "Home");
user_pref("calendar.registry.e7e8e370-4f03-488c-9dd7-2a496b88f79c.type", "storage");
user_pref("calendar.registry.e7e8e370-4f03-488c-9dd7-2a496b88f79c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/New_York");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1707724406488");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1707724425);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231215200246");
user_pref("extensions.lastAppVersion", "115.6.0");
user_pref("extensions.lastPlatformVersion", "115.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"da1c7d24-c4ef-4540-8706-cbafd07b6b5c\",\"google@search.mozilla.org\":\"0118ce5a-1b0d-494c-80ed-8d4c22a00cb5\",\"ddg@search.mozilla.org\":\"df5b0d82-34e9-4c97-8933-9ed4b5e7ce0d\",\"amazondotcom@search.mozilla.org\":\"33079224-fe06-4a53-ba26-ec29be9dc896\",\"wikipedia@search.mozilla.org\":\"8877bbe6-e3a3-42b3-a0a8-31eef2c4ac53\",\"bing@search.mozilla.org\":\"d235f232-ee19-4e6c-8942-a15db5c0fa1b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1707724711);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "04f0bc6f-0936-41f1-a7ff-943057a4eda");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.6.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1707724711);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1707724711);
user_pref("toolkit.startup.last_success", 1707724391);
user_pref("toolkit.telemetry.cachedClientID", "eb13f9fd-1ef7-45b5-88f9-bcb35afef2d7");
user_pref("toolkit.telemetry.previousBuildID", "20231215200246");
